footer component
202306-NEA-DZ-FEW/team-a pull request #13
Opened 2023-10-14 01:08 UTC by rahemSorour

Created the footer component along with the tests

#Screenshot 
![image](https://github.com/202306-NEA-DZ-FEW/team-a/assets/86094605/c7668ff4-dd3d-464f-9d45-0851998fd91e)
![image](https://github.com/202306-NEA-DZ-FEW/team-a/assets/86094605/3b582eee-3789-4323-a636-7b3a2fa32bdc)

2023-10-15 22:06 UTC, riadhmouamnia approved these changes
## Approval Review for "Footer" PR

**Reviewer:** @riadhmouamnia 

Excellent work on the "Footer" The footer includes all the necessary links, has snapshot testing in place, and is well-prepared for merging.

This PR is good to go. Well done!

@riadhmouamnia

2023-10-16 01:27 UTC, farouk26 approved these changes

2023-10-16 08:39 UTC, tech-chieftain commented
Love the interaction that happened here. Good job team! ⭐

2023-10-16 11:10 UTC, riadhmouamnia requested changes

2023-10-16 11:10 UTC, riadhmouamnia commented on src/components/Footer/index.jsx
> +    <div className='bg-neutral py-10 px-6 text-white fixed bottom-0 w-full'>
## Request for Change Review - "Footer" PR

**Reviewer:** @riadhmouamnia 

Thank you for your work on the "Footer" PR. This is a little late but I've identified a couple of issues that need to be addressed before merging:

1. **Positioning Bug**: The footer currently has a `position: fixed` property in its CSS classes, causing it to overlay other sections and always appear at the bottom of the page.

2. **Branch Update**: The branch is not up to date with the `develop` branch. so we need to rebase or merge the latest changes from `develop` into this branch to resolve any conflicts and ensure alignment with the most recent codebase.

I'll handle the necessary fixes for these issues myself. and then push the changes so don't worry about this issue @rahemSorour and focus on your other task!

@riadhmouamnia

2023-10-16 11:12 UTC, riadhmouamnia approved these changes

2023-10-16 11:13 UTC, merged