82 translation issue
202306-NEA-DZ-FEW/team-a pull request #83
Opened 2023-11-08 20:08 UTC by Bushra369

2023-11-08 20:26 UTC, rahemSorour requested changes

2023-11-08 20:26 UTC, rahemSorour commented on public/locales/fr/dashboard.json
> +    "namePlaceholder": "Entrez votre nom complet",
Change the verb to the formal speech

2023-11-08 20:26 UTC, rahemSorour commented on public/locales/fr/dashboard.json
> +    "nameLength": "Le nom doit comporter moins de 20 caractères",
Make it 30 characters

2023-11-08 20:26 UTC, rahemSorour commented on public/locales/fr/dashboard.json
> +    "emailPlaceholder": "Entrez votre email",
Change the verb to the formal speech as well

2023-11-08 20:26 UTC, rahemSorour commented on public/locales/fr/dashboard.json
> +    "locationRequired": "L'emplacement est requis"
Change "L'emplacement" to Willaya

2023-11-16 16:26 UTC, riadhmouamnia approved these changes

2023-11-16 16:27 UTC, rahemSorour approved these changes

2023-11-16 16:34 UTC, merged