95 404 page UI enhancement
202306-NEA-DZ-FEW/team-a pull request #97
Opened 2023-11-17 18:20 UTC by Bushra369

fixes #95 

I've implemented the 404 error page, and I'd like some feedback on its design and functionality.

![image](https://github.com/202306-NEA-DZ-FEW/team-a/assets/138239945/11a50a4d-3cc1-46ec-956b-d684e0c807be)

![image](https://github.com/202306-NEA-DZ-FEW/team-a/assets/138239945/90ab0191-9b9b-409b-b7c1-bd0d61aeb7be)

2023-11-17 20:04 UTC, liliumorion requested changes
we need an image with a colors closer to our palette if possible

2023-11-17 20:32 UTC, riadhmouamnia commented on public/images/404.svg
I think if we are going to change colors we should change it to red because our primary color is green and it indicates a success state instead of an error state since this page should indicate an error page!
@Bushra369 @liliumorion

2023-11-17 20:36 UTC, liliumorion commented on public/images/404.svg
i suggest a different image.

2023-11-18 17:14 UTC, rahemSorour approved these changes

2023-11-18 17:14 UTC, farouk26 approved these changes

2023-11-18 17:14 UTC, liliumorion approved these changes

2023-11-18 17:17 UTC, riadhmouamnia approved these changes
Looks neat now! you can merge now.

2023-11-18 17:18 UTC, merged